repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.30.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        types: [go]
        language: golang
        pass_filenames: false
        entry: golangci-lint run --fix
