repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.24.2
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: ensure-protolint
        name: ensure protolint
        language: system
        entry: task
        args: [protolint]
        always_run: true
        pass_filenames: false
      - id: protolint
        name: protolint
        language: system
        entry: protolint
        args: [lint, ./protos]
        always_run: true
        pass_filenames: false
      - id: ensure-buf
        name: ensure buf
        language: system
        entry: task
        args: [buf]
        always_run: true
        pass_filenames: false
      - id: buf-lint
        name: buf check lint
        language: system
        entry: buf
        args: [check, lint]
        always_run: true
        pass_filenames: false
      - id: buf-breaking
        name: buf check breaking
        language: system
        entry: buf
        args: [check, breaking, --against-input, ".git#branch=master"]
        always_run: true
        pass_filenames: false
