version: "2"

vars:
  BUF_DIR: /usr/local/bin
  BUF_VERSION: 0.21.0
  PROTOLINT_DIR: /usr/local/bin
  PROTOLINT_VERSION: 0.26.0
  UNAME_ARCH:
    sh: uname -m
  UNAME_OS:
    sh: uname -s

tasks:
  buf:
    cmds:
      - |
        if [ "{{.SYSTEM_BUF_VERSION}}" != "{{.BUF_VERSION}}" ]; then
          sudo curl -fsSL \
            "https://github.com/bufbuild/buf/releases/download/v{{.BUF_VERSION}}/buf-{{.UNAME_OS}}-{{.UNAME_ARCH}}" \
            -o "{{.BUF_DIR}}/buf"
          sudo chmod +x {{.BUF_DIR}}/buf
        fi
    vars:
      SYSTEM_BUF_VERSION:
        sh: buf -v 2>&1 || true

  protolint:
    cmds:
      - |
        if ! grep -q "{{.PROTOLINT_VERSION}}" <<< "{{.SYSTEM_PROTOLINT_VERSION}}"; then
          TMP_DIR=$(mktemp -d)
          cd ${TMP_DIR}
          curl -fsSL \
            "https://github.com/yoheimuta/protolint/releases/download/v{{.PROTOLINT_VERSION}}/protolint_{{.PROTOLINT_VERSION}}_{{.UNAME_OS}}_{{.UNAME_ARCH}}.tar.gz" \
            -o "protolint.tar.gz"
          tar -xzf protolint.tar.gz
          sudo mv protolint "{{.PROTOLINT_DIR}}/"
          rm -rf ${TMP_DIR}
        fi
    vars:
      SYSTEM_PROTOLINT_VERSION:
        sh: protolint version || true

  fmt:
    cmds:
      - protolint lint -fix ./protos

  lint:
    cmds:
      - pre-commit run --all-files

  _gen:
    cmds:
      - rm -rf .{{.OUT_DIR}}/go
      - mkdir -p .{{.OUT_DIR}}/go
      - |
        docker run --rm \
          -v $(pwd)/protos:/protos \
          -v $(pwd){{.OUT_DIR}}:{{.OUT_DIR}} \
          -w /protos \
          thethingsindustries/protoc:3.1.27 \
          --experimental_allow_proto3_optional \
          --proto_path=/protos \
          --go_out=plugins=grpc:{{.OUT_DIR}}/go \
          --go_opt=paths=source_relative \
          /protos/**/**/*.proto
    vars:
      OUT_DIR: "{{.OUT_DIR}}"

  gen:
    cmds:
      - task: _gen
        vars:
          OUT_DIR: /gen

  gen:local:
    cmds:
      - rm -r ./local
      - task: _gen
        vars:
          OUT_DIR: /local
