export const KO_KR_DICTS = {
  'EMAIL': '이메일',
  'NAME': '이름',
  'LOGIN': '로그인',
  'LOGOUT': '로그아웃',
  'RECRUTING_POSITIONS': '채용중인 포지션',
  'VIEW_MY_APPLICATION': '내 지원이력 보기',
  'POSITION_CATEGORY': '모집분야',
  'POSITION': '포지션',
  'MORE': '더 알아보기',
  'APPLY': '지원하기',
  'CONFIRM': '확인',
  'SKIP_FOR_NOW': '구경만 할래요',
  'REMOVE': '삭제',
  'CREATE_NEW_POSITION': '새 포지션 생성',
  'DESCRIPTION': '설명',
  'DETAILS': '상세 보기',
  'BACK': '뒤로가기',
  'CANCEL_TO_CREATE': '생성 취소',
  'SAVE': '저장',
  'CREATE': '생성',
  'POSITION_NAME': '포지션 이름',
  'POSITION_SUMMARY': '포지션 요약 소개',
  'POSITION_DETAILED_DESCRIPTION': '포지션 상세 소개',
  'PARAGRAPH': '문단',
  'TITLE': '제목',
  'CONTENT': '내용',
  'ADD_ROW': '행 추가',
  'ADD_PARAGRAPH': '문단 추가',
  'EXAMINATING_APPLICATION': '서류 검토중',
  'SCREENING': '전형 진행중',
  'END_SCREEN': '전형 종료',
  'ONBOARDING': '온보딩 진행중',
  'CODING_TEST': '코딩테스트',
  'CHECK_DOCUMENT': '서류 확인',
  'APPLY_DATE': '지원일',
  'PASS': '합격',
  'FAILURE': '불합격',
  'REVIEW_DOCUMENT': '서류 검토',
  'REGISTER_REFERRAL': '추천서 등록',
  'REGISTER_APPLICANT': '지원자 등록',
  'MORE_THAN_FIVE_DAYS': '5일 이상',
  'WAITING_APPLICANTS': '기다리고 있는 지원자 😥',
  'WAITING_FOR_EXAMINATING_APPLICANT': '서류 검토를 기다리고 있는 지원자',
  'NEED_TO_CHANGE_SCREENING_STEP_APPLICANT': '전형 단계 변경이 필요한 지원자',
  'SCREENING_STEP': '전형 단계',
  'ON_SCREENING_APPLICANT': '전형 진행중인 지원자',
  'PASSED_APPLICANT': '최종 합격한 지원자',
  'FAILED_APPLICANT': '불합격한 지원자',
  'ONBOARDING_APPLICANT': '온보딩 진행중인 지원자',

  'APPLY_CONFIRM_MESSAGE': '$1에 지원하시겠습니까?',
  'APPLICATION_ACCEPTED': '지원서가 접수되었습니다!',

  'SELECT_POSITION_TO_REMOVE': '삭제할 포지션을 선택해주세요.',

  'HEELO_MESSAGE': '님, 안녕하세요!',
  'LOGIN_MODAL_MESSAGE_1': '안녕하세요! ',
  'LOGIN_MODAL_MESSAGE_2': '에 관심이 있으신가요?',
  'LOGIN_MODAL_MESSAGE_3': '간단한 정보입력을 통해 ',
  'LOGIN_MODAL_MESSAGE_4': '에 지원해보세요!',

  'DASHBOARD': '대시보드',
  'APPLICATION_MANAGEMENT': '지원 현황 관리',
  'POSITION_MANAGEMENT': '포지션 관리',
  'FORM_MANAGEMENT': '양식 관리',

  'CONFIRM_REMOVE_POSITION_MESSAGE': '선택한 $1개의 포지션을 삭제하시겠습니까?',
  'EMPTY_POSITION': '생성된 포지션이 없습니다.',
  'LOADING_DATA': '데이터를 불러오는 중입니다.',
  'CONFIRM_PASS_APPLICANT_MESSAGE': '선택한 $1명의 지원자를 합격 처리하시겠습니까?',
  'CONFIRM_FAILURE_APPLICANT_MESSAGE': '선택한 $1명의 지원자를 불합격 처리하시겠습니까?',
  'NO_APPLICANT': '해당하는 지원자가 없습니다.',
  'ENTER_SCREENING_STEP_NAME': '다음으로 진행하는 전형 명칭을 입력해주세요.',
  'CONTINUE_SCREENING': '최종 합격을 하시겠습니까?\n전형을 계속 진행시키려면 \'취소\'를 눌러주세요.',

  'ERROR_INVALID_PATH': '올바르지 않은 경로로 접근하였습니다.',
  'ERROR_APPLICATION_ACCEPTANCE_FAILED': '지원에 실패하였습니다',
  'ERROR_FETCH_POSITION_FAILED': '포지션 정보를 가져오는데에 실패하였습니다.',
  'ERROR_INVALID_ID_OR_PASSWORD': '올바른 아이디 및 패스워드를 입력해주세요.',
  'ERROR_SAVE_POSITION_CHANGE_FAIELD': '포지션 내용 변경 저장을 실패하였습니다.',
  'ERROR_CREATE_NEW_POSITION_FAILED': '새 포지션 생성에 실패하였습니다.',
  'ERROR_REMOVE_POSITION_FAILED': '포지션 삭제에 실패하였습니다.',
  'ERROR_FETCH_POSITION_LIST': '포지션 목록을 받아오는데에 실패하였습니다.',
  'ERROR_LOGOUT_FAILED': '로그아웃에 실패하였습니다.',
  'ERROR_NO_SELECTED_APPLICANT': '선택한 지원자가 없습니다 😥',
  'ERROR_FETCH_APPLICANT_FAILED': '지원자 목록을 받아오는데에 실패하였습니다',
  'ERROR_SAVE_APPLICANT_CHANGE_FAIELD': '지원자 상태 변경에 실패하였습니다',
  'ERROR_SCREENING_STEP_NAME_CANNOT_BE_BLANK': '전형 명칭을 입력해주세요',

  'COMPANY_SAMPLE_TITLE': '가슴 뛰는 목표,\n목적이 있는 삶',
  'COMPANY_SAMPLE_DESCRIPTION': '우리는 \'채용의 모든 문제를 해결하겠다\'는 목표에 마음이 움직여 여기에 모였습니다. $1팀은 모두가\n같은 목표를 향해 달립니다. 불가능한 것을 꿈꾸고, 그걸 가능하게 만드는 동료들과 함께 열정적으로\n일하고 있습니다. 가슴이 설레시나요? 지금이 바로 $1팀에 합류할 때입니다.',
};
